Feature#25 incidence
BC-NOV-20-Proyectos/alerta-covid-web-team01 pull request #35
Opened 2021-04-27 20:44 UTC by mariormt17

# Description
- In this PR we implemented the functionality of the incidents on the web and api.
- In the api only the index, create and update methods were created.
  
  ## Screenshots 
![Captura de Pantalla 2021-04-27 a la(s) 3 35 38 p m](https://user-images.githubusercontent.com/38173659/116309347-43c29980-a76e-11eb-918d-da63d31222f4.png)
![Captura de Pantalla 2021-04-27 a la(s) 3 44 12 p m](https://user-images.githubusercontent.com/38173659/116310307-71f4a900-a76f-11eb-9017-e87d9a06b21d.png)

2021-04-27 20:57 UTC, MiguelOcegueraM approved these changes, later dismissed
nice code mates, too clean

2021-04-27 20:57 UTC, MiguelOcegueraM commented on alerta-covid/app/controllers/api/v1/incidences_controller.rb
> +  end
nice!

2021-04-27 20:57 UTC, MiguelOcegueraM commented on alerta-covid/app/views/places/_form.html.erb
> +    <%= select_tag 'place[area_id]', options_from_collection_for_select(@areas, "id", "name", @place.area_id), include_blank: "Select Area", class: 'form-control', id: 'select-area'  %>
nice refactor

2021-04-27 21:36 UTC, ArielMD submitted a review, later dismissed
Nice job team

2021-04-27 21:36 UTC, ArielMD commented on alerta-covid/app/models/place.rb
> +  after_destroy :destroy_qr_code
Nice, callbacks

2021-04-27 21:40 UTC, FranckZnt19 requested changes
all it's fine, but this task does not have unit tests neither in web module nor in appi. it's  necessary to place them.

2021-04-28 15:17 UTC, jaimelr reviewed
Please review the indentation of the files (must be two spaces), check on the spaces of assignments for example: `@areas=Area.all`

Also this PR seems to include changes that are not related to Incidences, usually Pull Request must focus on one specific topic is possible. I'm seeing Incidences, Department and QR code updates in the same branch. If they all need to be in this PR, please add it to the PR description.

2021-04-28 15:17 UTC, jaimelr commented on alerta-covid/app/models/covid_test.rb
> +  has_many  :incidence
I would expect this to be plural: `incidences`, what do you think? 
> The name of the other model is pluralized when declaring a has_many association.

See: Rails Guides [2.3 The has_many association](https://guides.rubyonrails.org/association_basics.html#has-many-association-reference)

2021-04-28 15:17 UTC, jaimelr commented on alerta-covid/app/models/user.rb
> +  has_many :incidence
See my previous comment.

2021-04-28 15:17 UTC, jaimelr commented on alerta-covid/app/controllers/incidences_controller.rb
> +    @user_symptoms = @incidence.symptoms.collect{|p|p.id}
`@user_symptoms = @incidence.symptoms.collect { |p| p.id }`

2021-04-28 15:17 UTC, jaimelr commented on alerta-covid/app/controllers/incidences_controller.rb
> +    puts("desde set params #{params.require(:incidence).inspect}")
Is this a debug line?

2021-04-28 17:25 UTC, FranckZnt19 approved these changes

2021-04-28 17:29 UTC, ArielMD approved these changes
Nice

2021-04-28 22:08 UTC, jaimelr approved these changes

2021-04-28 22:17 UTC, merged